version: '3.9'
services:
  app:
    build: .
    container_name: project1_app
    ports:
      - '4000:4000'
    env_file: .env
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  pgdata:
